### ISSUE TITLE
Countdown timer needs to be pressed twice

### ISSUE THREAD

**Issue by jtracker2011** [fellinga/node-red-contrib-ui-countdown-timer-switch#3]
I have an issue which may be unique to me.  
When I press a timer number such as 2, 5 or 10, it turns the device on but does not set the off time and the device does not go off. 
If I press that timer number a second time it sets the off time and everything works fine.
I changed the Payload to on/off and added a topic but that should not affect the behavior.

any recommendations?

**Comment by fellinga** [comment]
Hi @jtracker2011,

what browser are you using? Same behaviour in Edge or Chrome?

**Comment by jtracker2011** [comment]
Android phone and tablet.  Primarily using Firefox but same behavior in
Chrome.

Tablet is android 11

**Comment by fellinga** [comment]
I've tried this on multiple devices and servers and it never happend to me. I also did not get any feedback from anyone else so I would expect this to be a unique issue to you. Maybe a browser plugin or something like that?

**Comment by jtracker2011** [comment]
Thanks for looking into it.
