### ISSUE TITLE
Too much empty space?

### ISSUE THREAD

**Issue by BayerSe** [fellinga/node-red-contrib-ui-countdown-timer-switch#4]
Hi,

I came across your node that serves my purpose perfectly: to turn off my air conditioner with some delay. Thank you for making it public!

In my dashboard, there is quite some empty space - is this intended?

![image](https://user-images.githubusercontent.com/14983438/175831350-58c170b5-edf8-4dee-87ec-6f8023435c08.png)

Regards
Sebastian

**Comment by fellinga** [comment]
hi @BayerSe,

thanks for your feedback, I am glad it fits your needs!

I have just released 1.4.1 which should make sizing a little more flexibel. What didn't change though is the fact that the node does need around 150px in height but you can now force it to be smaller if are okay with a scrollbar. This is why:

![sizing](https://user-images.githubusercontent.com/26927863/176010428-f59c887d-c842-420a-90fc-3023317c10de.png)

You could replace your label "Klimaanlage" with the label that you can configure in the node itself, maybe that would save a little space.

Please let me know if this helps!

**Comment by BayerSe** [comment]
Hi,

many thanks for the super quick response and help!

With version 1.4.1, the layout in "auto" mode looks like this
![image](https://user-images.githubusercontent.com/14983438/176013680-fead2a87-5cf6-4d16-951c-29a16af018df.png)

which still uses a bit too much space.

When I set the size to 6x2, though, the layout fits perfectly.

![image](https://user-images.githubusercontent.com/14983438/176013806-05021765-5e57-4fed-9de1-7f0b6f6d2862.png)


Many thanks!
